apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://rancher.kubedrop.io/k8s/clusters/local"

users:
- name: "local"
  user:
    token: "kubeconfig-user-vnb5rfb6jd:mv8tpwc5jhkprng7jxzv8lrn4lprxk7qplgcqrk9q6p9hwxv7mck7h"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
