apiVersion: v1
kind: Service
metadata:
  name: "{{ include "wordsmith.fullname" . }}-web"
  labels:
    app: web
    {{- include "wordsmith.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.targetPort }}
      name: web
  selector:
    app: web
    {{- include "wordsmith.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "wordsmith.fullname" . }}-web"
  labels:
    app: web
    {{- include "wordsmith.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: web
      {{- include "wordsmith.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: web
        {{- include "wordsmith.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image }}:{{ .Values.web.tag }}"
          ports:
            - containerPort: {{ .Values.web.targetPort }}
              name: web
