apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deploy.yaml
  - service.yaml
images:
  - name: rajivnix/wordsmith-web
    newTag: "latest"
generatorOptions:
  disableNameSuffixHash: true