apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-cache
  namespace: jenkins
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com

spec:
  storageClassName: gp2
  volumeMode: Filesystem

  accessModes:
    - ReadWriteOnce  # This specifies the access mode for the PVC
  resources:
    requests:
      storage: 20Gi  # This specifies the requested storage capacity
